replicas: 2
container:
  containerPorts:
    port: 80
    protocol: TCP
    targetPort: 3000
  image:
    path: public.ecr.aws/f8u4w2p3/rust/rust-service-1:latest
  environmentVariables:
    bindAddress: 0.0.0.0:3000
    rustLog: "INFO"


