apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-deployment
  labels:
    app: rust-service-1
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: rust-service-1
  template:
    metadata:
      labels:
        app: rust-service-1
    spec:
      containers:
        - name: web-api
          image: {{ .Values.container.image.path }}
          ports:
            - containerPort: {{ .Values.container.containerPorts.targetPort }}
              name: web-port
              protocol: {{ .Values.container.containerPorts.protocol }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
